name: Mocha Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd backend/
          npm ci

      - name: Run tests
        working-directory: backend/
        run: npm test
        timeout-minutes: 2  # Set a lower timeout value, e.g., 2 minutes
